version: '3.8'

services:
  web:
    build:
      context: ./app
    container_name: silence-remover
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/silence-remover/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /var/lib/docker/volumes/certbot-etc/_data:/etc/letsencrypt:ro
      - certbot-var:/var/lib/letsencrypt

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    entrypoint: >
      sh -c "trap exit TERM; 
             while :; do sleep 12h & wait $${!}; certbot renew --webroot -w /var/lib/letsencrypt --quiet; done"

volumes:
  certbot-etc:
  certbot-var:
