name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Free port 80
        run: |
          echo "Freeing port 80..."
          sudo fuser -k 80/tcp || echo "Port 80 already free"
          docker ps --format '{{.ID}} {{.Ports}}' | grep ':80->' | awk '{print $1}' | xargs -r docker stop

      - name: Clean containers and networks
        run: |
          echo "Cleaning containers and networks..."
          docker ps -a -q --filter "name=silence-remover" | xargs -r docker rm -f
          docker ps -a -q --filter "name=certbot" | xargs -r docker rm -f
          docker container prune -f || true
          docker network prune -f || true

      - name: Build containers (no cache)
        run: docker compose -f docker-compose.prod.yml build --no-cache

      - name: Deploy
        run: docker compose -f docker-compose.prod.yml up -d --force-recreate web

      - name: Set restart policy (optional)
        run: |
          docker update --restart unless-stopped silence-remover || true
